[2023-07-21 19:53:08,515][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-21 19:53:08,650][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-21 19:53:08,698][classifier.train][INFO] - Instantiating loggers...
[2023-07-21 19:53:08,699][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 46, in train
    logger: List[Logger] = instantiate_loggers(cfg.get("logger"))
                           ^^^^^^^^^^^^^^^^^^^
NameError: name 'instantiate_loggers' is not defined
[2023-07-21 19:53:08,704][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/outputs/2023-07-21/19-53-08
